name: Deploy to Bluehost via FTP

on:
  push:
    branches:
      - main # Se ejecutará cuando hagas push a la rama 'main'

jobs:
  deploy:
    name: Upload files to Bluehost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: czt.hsk.mybluehost.me # Reemplaza con el servidor FTP de Bluehost si es diferente
          username: ${{ secrets.FTP_USERNAME }} 
          password: ${{ secrets.FTP_PASSWORD }} 
          local-dir: ./ # Carpeta local a sincronizar
          server-dir: hernanfilippini.com/ # Asegúrate de que esta sea la ruta correcta en Bluehost
